name: Build and Deploy demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: npm i -g pnpm && pnpm i && cd  ./packages/vuepress-plugin-blog-sync && pnpm build && cd ../demo && pnpm build
          BUILD_DIR: docs/.vuepress/dist/
